name: custom_libp2p
description: Library for use LibP2P with support for android, ios, macos, windows, linux and web
publish_to: 'none'
version: 0.0.0
homepage: https://github.com/DecentRealized/flutter-custom-libp2p

environment:
  sdk: '>=3.0.3 <4.0.0'

false_secrets:
 - /example/lib/*.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.0.2
  flat_buffers: ^2.0.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.DecentRealized.custom_libp2p
        pluginClass: CustomLibP2PPlugin
      ios:
        pluginClass: CustomLibP2PPlugin
      web:
        pluginClass: CustomLibP2PPlugin
        fileName: web/custom_libp2p_web.dart
      macos:
        pluginClass: CustomLibP2PPlugin
      linux:
        pluginClass: CustomLibP2PPlugin
      windows:
        pluginClass: CustomLibP2PPlugin
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
